version: '3.3'
services:
  app:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/code/app
    ports:
      - 80:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

  db:
    image: mysql:8
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'employees'
      # So you don't have to use root, but you can if you like
      MYSQL_ROOT_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - data:/var/lib/mysql

# Names our volume
volumes:
  data:
  app: